### ISSUE TITLE
click dropdown scrollbar to scroll, the result disappear

### ISSUE THREAD

**Issue by wwang2016** [darrenjennings/vue-autosuggest#102]
Hi,

This issue seems to stay unresolved.

I downloaded the latest files from github and played around with the samples. The window disappears once the mouse does not scroll and keyup.

The following sample sites have the same issue:
https://darrenjennings.github.io/vue-autosuggest/
https://darrenjennings.github.io/vue-autosuggest/storybook/

Can you confirm if this issue has been fixed?

Thanks,

Wayne

**Comment by darrenjennings** [comment]
Can you confirm this is on IE or Edge? Those are the only browsers I know this happens on. Unfortunately I am unable to test a fix at the moment.

**Comment by wwang2016** [comment]
I tested the above links on Chrome v72 and Firefox v65. The windows just disappear once the mouse that drags the scroll bar is released.

**Comment by darrenjennings** [comment]
@wwang2016 since I am not able to reproduce, but this issue comes up quite often, I will leave this open and if anyone would like to investigate, check out the function causing issues:

https://github.com/darrenjennings/vue-autosuggest/blob/b825be24211450da3700898ade30701ecdd3b491/src/Autosuggest.vue#L455-L458

**Comment by darrenjennings** [comment]
I was able to reproduce. Looks like an issue with mac osx system settings `show scrolls bars > "when scrolling"`. I have a fix locally. Will try and find some time to get it up soon.
