### ISSUE TITLE
[Feature request] Use portal to render results

### ISSUE THREAD

**Issue by DarkSouL11** [darrenjennings/vue-autosuggest#113]
I have a particular case where I need to render the autosuggest component inside a component which has `overflow: hidden` on it, this makes only a part of the results container visible.

![Screenshot 2019-05-28 at 10 12 06 AM](https://user-images.githubusercontent.com/8626394/58451432-1360c380-8131-11e9-91de-c863147ebcea.png)

If [portals](https://github.com/LinusBorg/portal-vue) were used then there can be more flexibility on where the results container should be rendered in the DOM.

**Comment by darrenjennings** [comment]
@DarkSouL11 I agree this could be nice. I tried to implement it at one point without `vue-portal` as a dependency, but didn't seem to work like I wanted. some of the features such as ARIA or highlight classes depend on the results being selectable as a child of the auto-suggest element e.g. https://github.com/darrenjennings/vue-autosuggest/blob/242dd4dee084d5f6133c09b88da7f9e87f7502be/src/Autosuggest.vue#L508

Since it's not trivial to implement wouldn't mind help investigating a solution or if you know of other components with prior art we could borrow.

**Comment by DarkSouL11** [comment]
@darrenjennings One solution I can think(doesn't use portals at all) of is using `position: fixed` on results container and calculating its left and top offsets manually.

**Comment by darrenjennings** [comment]
Closing since, for now, it is acceptable to render results in the same html location as the `<input />` and it follows from w3c examples: https://w3c.github.io/aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html
