### ISSUE TITLE
sectionConfig with type examples

### ISSUE THREAD

**Issue by tmelliottjr** [darrenjennings/vue-autosuggest#175]
Are there are any examples available demonstrating how to use a sectionConfig with a custom type/component? 

I have a use case where I'd like to override the mouseenter/mouseleave functionality and this seems like it "should" do the trick. 

Specifically, what is required/not required for this custom component and is the component required to be registered globally?

**Comment by darrenjennings** [comment]
@tmelliottjr the custom component behavior was pseudo-deprecated with version 2.0. I did not hear of anyone actually using it and it was actually pretty painful to use because it would mean extending DefaultSection or copy pasting the template. If you did attempt it, the component would indeed need to be required globally. It might still work in some way, but I haven't tested it.

The docs used to use a custom section to demonstrate, but I moved defaultsection to use a render function instead so the extend/template override might not work:
https://github.com/darrenjennings/vue-autosuggest/blob/v1.1.0/docs/UrlSection.vue
https://github.com/darrenjennings/vue-autosuggest/blob/v1.1.0/docs/App.vue#L83

**Comment by tmelliottjr** [comment]
@darrenjennings Thanks for the quick reply! 

I got this working with the examples in the repo by using DefaultSection.js as a template and modifying it to my needs. It seemed to work perfectly. The issue I'm having in my local implementation is that I'm using a custom `render-suggestions` function and the item object is mostly empty. I end up with something like:

`{
name: "default"
type:  "base-section"
label: undefined
item: undefined
}`

I'm sure the problem exists elsewhere, but it's proving elusive.

**Comment by darrenjennings** [comment]
if you have a codesandbox I can take a look

**Comment by tmelliottjr** [comment]
I'm going to research this a bit more before I ask you to look at anything. Also, I'm not sure I have a small enough repro to show yet.

**Comment by tmelliottjr** [comment]
It appears that there might be a build step that is missing in my local implementation. What I'm seeing is that in the render function in the examples this is being captured `var _this = this;` while this isn't happening locally for me.

**Comment by darrenjennings** [comment]
Closing since section config 'type' isn't really supported anymore. happy to discuss if you have more information or a codesandbox repro.
