### ISSUE TITLE
move `on-suggested` to an event

### ISSUE THREAD

**Issue by Haroenv** [darrenjennings/vue-autosuggest#58]
- `vue-autosuggest` version: 1.5.0

Relevant code or config

```vue
<vue-autosuggest
  :suggestions="indicesToSuggestions(indices)"
  :on-selected="selectHandler"
  :input-props="{
    style: 'width: 100%',
    onInputChange: refine,
  }"
/>
```

Problem description:

`_onSelected` seems to be a fine abstraction, but it's more of a React pattern than a Vue pattern. For that I'd change that to `this.$emit('selected', ...data)`. I'd do a PR but wasn't completely sure what the code all meant :)

Suggested solution:

change to an event for `"selected"` (with backwards compatibility, like for the other events)

```vue
<vue-autosuggest
  :suggestions="indicesToSuggestions(indices)"
  @selected="selectHandler"
  :input-props="{
    style: 'width: 100%',
    onInputChange: refine,
  }"
/>
```

**Comment by darrenjennings** [comment]
I had originally left off custom listeners because I usually see events passed as callback props, and `@` left for native DOM events. I also borrowed much of my inspiration from react-autosuggest. However, I like this API, as it makes the component easier to tell which props are events. Should be an easy fix with backwards compatibility as you say. Thanks!
