### ISSUE TITLE
onInputChange only fired after keyboard is closed on android 

### ISSUE THREAD

**Issue by luhegi** [darrenjennings/vue-autosuggest#70]
onInputChange method only fired after keyboard on android phone is closed, is it possible to listen change without close android keyboard?

**Comment by luhegi** [comment]
solved using `@input='evt=>fetchResults(evt.target.value)'`
in
````
<vue-autosuggest`
			    :suggestions="suggestions"
			    :getSuggestionValue="getSuggestionValue"
			    :sectionConfigs="sectionConfigs"
			    :inputProps="{id:'searchBarInput', onInputChange: this.fetchResults, placeholder:'Cari Perkakas atau Brand','autocomplete':'off', 'aria-label': 'Search Bar'}"
			    @input='evt=>fetchResults(evt.target.value)'
			    v-on:keyup.enter="goToSearch"
			    style="text-transform: capitalize;padding:0;width: 100%;"
			>
			<template slot-scope="{suggestion}">
	                <!-- suggestion.name corresponds to which section the item is in -->
	                <div v-if="suggestion.name === 'products'">
	                    <!-- suggestion.item corresponds to the suggestion object -->
	                    <img :src="suggestion.item.firstimage" class="search-thumb">
	                    <span class="suggestion-brand">{{suggestion.item.manufacturer.name}}</span>
	                    <span class="suggestion-model">{{suggestion.item.model}}</span>
	                    <span class="suggestion-name">{{suggestion.item.name}}</span>
	                </div>
	            <div v-else>{{suggestion.item.name}}</div>
	          </template>
</vue-autosuggest>
````

**Comment by darrenjennings** [comment]
cool. interested to see what you're building!

**Comment by ghost** [comment]
I came up with same problem. I applied this solution, problem now is that it's calling `fetchResults` twice, which means two same queries.

Is there another way we can "force" the `@input` event so that it works on Android?

**Comment by darrenjennings** [comment]
@FernandoSMonter it looks like @luhegi is using 1.x. If you update to latest 2.x beta (see instructions here: https://github.com/darrenjennings/vue-autosuggest/issues/92) then you will not have to implement both `inputProps.onInputChange` _and_ `@input`, since 2.0 removes `onInputChange` in favor of native `@input` event. This should remove your double invocations. Keeping this issue closed, but if you are experiencing issues still, please try to recreate in the codesandbox environment and open another issue, mentioning this one. Thanks!
