### ISSUE TITLE
How to make the footer element clickable?

### ISSUE THREAD

**Issue by lorro** [darrenjennings/vue-autosuggest#75]
Hi,

What I would like to achieve is an autocomplete widget with the offered posibility to save the typed string to a database. The presence of a footer slot in this component seemed a great fit but I'm having some trouble. A click on this footer slot should open a modal with a form in my case.

But I can't react to a click on the footer it seems. Could this be? I defined a click handler on the content in this footer slot, but the dropdown just closes and doesn't trigger any event?

Does anyone have a suggestion how I could tackle this?

Thanks

**Comment by lorro** [comment]
Thanks for pointing that out :)
Looks like a good fit, thanks!

**Comment by smsugumar5** [comment]
Error "Cannot set property 'loading' of undefined" when i trying to access `this.$refs.autosuggest.loading = false`

**Comment by darrenjennings** [comment]
@smsugumar5 did you put a ref on the autosuggest element?

e.g. 
```html
<vue-autosuggest ref="autosuggest" ...
````

**Comment by smsugumar5** [comment]
Yes, I added ref="autosuggest"
`this.$refs.autosuggest.loading` is not working if passed to the method `shouldRenderSuggestions`

I tried using the code you provided on codesandbox in the NUXT framework, and also recorded a video here
[https://www.useloom.com/share/75ee8bf7342f4ca19a32959473ea8c98](url)

**Comment by puremana** [comment]
Couldn't the full example to work using Algolia data, without doing the value filtering yourself.

Ending up sacrificing the ability to select using the component (such as using up and down keys) and created my own select method on suggestion click.

Having 5+ methods to get a footer on click seems over the top to me. Could this possibly be refactored in the future to allow a simple @click method?

**Comment by darrenjennings** [comment]
@puremana sorry this is definitely a bit frustrating. There is a simpler way to do it without as much fanfare in 1.x versions which is utilizing @mouseup.stop on the item you're clicking in the footer:
https://codesandbox.io/s/vueautosuggest-api-clicking-things-in-the-headerfooter-bzdrp

With the latest beta (currently 2.0.0-beta.8) it's a bit better because shouldRenderSuggestion actually passes back a "loading" and "size" prop which helps with understanding if vue-autosuggest thinks you should be closing the suggestions or not. Demonstrated here:
https://codesandbox.io/s/x9z1lo20mo

Hope this helps!

**Comment by puremana** [comment]
Thank you for that. Unfortunately, I don't have any more time to spend on this at the moment so we have to make do with what we have got. I will try those implementations if we get any more time in the future.
